### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by mrexodia**
This compiles with LLVM 10 for Windows and the MSVC standard library:

`cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..`

Also includes fixes for gcc 8 and some CMake modernization supersedes #8

### CODE REVIEW

**Comment by lacc97** [comment]
Nice! I'll close my PR.

**Comment by mrexodia** [comment]
Yeah sorry about that, guess we were both working on it at the same time 😀

**Comment by lacc97** [comment]
No worries, yours was much further than mine.

I still have a few missing include errors on gcc10. There's a PR on your branch about that.

**Comment by mrexodia** [comment]
Thanks, will try gcc10 after I fixed the final weird linker errors for gcc8
:)

**Comment by mrexodia** [comment]
Did some more fixes and managed to compile everything with gcc10, will push
later tonight!

**Comment by alandefreitas** [comment]
Great work. Thanks.

**Pull request merged**
