### PR TITLE
Add minGW workflow Second Try

### PR DESCRIPTION
**Pull request by rath3t**
This PR should resolve the problems from #161, see also the discussion at: https://github.com/actions/virtual-environments/pull/3590

### CODE REVIEW

**Comment by rath3t** [comment]
Ok all checks passed but if you look at the Integration test. It says that it is passing. Even if it fails to find the matpolt++ package

**Comment by alandefreitas** [comment]
That looks great. Thanks!

> Ok all checks passed but if you look at the Integration test, it says that it is passing. Even if it fails to find the matplot++ package

The Integration test is allowed to fail for now because finding packages on windows is a little trickier, and we just haven't implemented that yet.

I see it's not generating the artifacts for MinGW yet, but that should be trivial to fix in the future.

**Comment by rath3t** [comment]
Thanks!

**Comment by alandefreitas** [comment]
Looks like the documentation action did its thing now! 😀
https://alandefreitas.github.io/matplotplusplus/community/contributors/

**Pull request merged**
