### PR TITLE
fix: install matplot_opengl in CMake

### PR DESCRIPTION
**Pull request by aminya**
Fixes the missing matplot_opengl install

### CODE REVIEW

**Comment by alandefreitas** [comment]
This target is very experimental and missing almost all features. I didn't think anyone wanted that installed.

In any case, I believe it would still need to find the dependencies in the cmake config file to work properly.

**Comment by aminya** [comment]
The installation only happens when the experimental option is enabled. Otherwise, it will not be installed

**Comment by alandefreitas** [comment]
> The installation only happens when the experimental option is enabled. Otherwise, it will not be installed

Yes. That's fine.

Have you tried using what it installs locally? Did it work? I would expect a few `find_dependency` in the config template for that to work.

**Comment by aminya** [comment]
Yes, I tested it. It actually works with vcpkg as well the platforms they test:
https://github.com/microsoft/vcpkg/pull/31229

**Comment by alandefreitas** [comment]
Thanks! :)

**Pull request merged**
