### PR TITLE
Feature/adopt clang format

### LINKED ISSUE #2: Suggestion: adopt ClangFormat for all files
Dear Alan,

thank you for sharing this awesome project.

I would like to suggest adopting [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html), and use one of its styles for the whole code base.
This would make contributing much easier.
I think now, just after the release, would be a good time to do that, before more people start contributing which I am sure they will :)

I am aware that this would mean kind of a blocker in the Git history, but I am certain it will pay off long-term.

Cheers

### PR DESCRIPTION
**Pull request by globberwops**
I have added a ClangFormat style file for the Google style, and applied it to the code base to resolve #2

### CODE REVIEW

**Comment by cguebert** [comment]
I tried to adapt the parameters to reduce the changes to existing code, and to start I suggest these:
```
IndentWidth: 4
NamespaceIndentation: All
ColumnLimit: 0
```

**Comment by dimztimz** [comment]
The Google style is terrible, mostly because of the indentation with 2 spaces. I'd rather base my style on LLVM which has indentation with 4 spaces. Secondly, I wouldn't create this big `.clang-format`, I'd rather use the command `BasedOnStyle` and few other commands that override the base to make the clang-format style be the closest to the one already used. See the official docs for [small example](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).

**Comment by dimztimz** [comment]
Since the author says in the issue #2 that he is following the Google style with some exceptions, 4-spaced indentation for example, a better starting point for the clang format would be only the following 4 lines (as @cguebert suggested)

```
BasedOnStyle:  Google
IndentWidth: 4
NamespaceIndentation: All
ColumnLimit: 0
```

**Comment by globberwops** [comment]
@dimztimz I agree on providing a minimal config file. Google Style would not have been my first choice either, but that's up to the author as you said.
@cguebert I would strongly advise against `NamespaceIndentation: All`. This seems just like a huge waste of space to me. I get your intention to though.

**Comment by alandefreitas** [comment]
Hey guys,

Don't worry too much about what "the author" said. Let's reach a consensus.

[]s,

**Comment by mrexodia** [comment]
I would propose waiting for a huge change in formatting until the library actually compiles, because as it is now there are a lot of errors

**Comment by alandefreitas** [comment]
Thanks for the feedback guys. 

I tried to consider all your comments at once and arrived at this [.clang-format](https://github.com/alandefreitas/matplotplusplus/blob/master/.clang-format) that seems to be a reasonable compromise between everything you guys said. I did that aside from this PR because of some conflicts with the other PRs. I hope that's ok.

More feedback is welcome. It's all open to change. Sorry for taking this long. I was reviewing a PR on some compilation errors. I hope you are being able to run the examples.

**Comment by globberwops** [comment]
> I did that aside from this PR because of some conflicts with the other PRs. I hope that's ok.

Sure, no worries Alan. The intention behind the PR was just to give a starting point.

Cheers

**Comment by alandefreitas** [comment]
Great. Thanks for the valuable help.

**Pull request closed without merging**
